# Generated by Django 5.2.7 on 2025-10-16 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0002_academicyear_subject_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examanalytics',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='learninganalytics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_analytics', to='students.student'),
        ),
        migrations.AddField(
            model_name='learninganalytics',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_analytics', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='predictiveanalytics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_analytics', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='systemusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceanalytics',
            unique_together={('class_room', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='examanalytics',
            unique_together={('exam',)},
        ),
        migrations.AlterUniqueTogether(
            name='learninganalytics',
            unique_together={('student', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='predictiveanalytics',
            unique_together={('student',)},
        ),
        migrations.AlterUniqueTogether(
            name='studentperformance',
            unique_together={('student', 'subject', 'academic_year', 'semester')},
        ),
    ]
