# Generated by Django 5.2.7 on 2025-10-16 15:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('classes', '0002_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_type', models.CharField(choices=[('regular', 'Regular Class'), ('exam', 'Examination'), ('practical', 'Practical'), ('lab', 'Laboratory'), ('field_trip', 'Field Trip'), ('other', 'Other')], default='regular', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to='teachers.teacher')),
            ],
            options={
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-date', '-start_time'],
                'unique_together': {('course', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('late_threshold_minutes', models.PositiveIntegerField(default=15, help_text='Minutes after which a student is marked late')),
                ('absent_threshold_minutes', models.PositiveIntegerField(default=30, help_text='Minutes after which a student is marked absent')),
                ('auto_mark_absent', models.BooleanField(default=True, help_text='Automatically mark absent students')),
                ('send_notifications', models.BooleanField(default=True, help_text='Send attendance notifications to parents')),
                ('require_excuse_notes', models.BooleanField(default=True, help_text='Require excuse notes for absences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_enrolled', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='classes.class')),
            ],
            options={
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('emergency', 'Emergency Leave'), ('family', 'Family Event'), ('medical', 'Medical Appointment'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('supporting_documents', models.FileField(blank=True, upload_to='leave_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='teachers.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('late_days', models.PositiveIntegerField(default=0)),
                ('excused_days', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Attendance Reports',
                'ordering': ['-academic_year', '-month'],
                'unique_together': {('student', 'academic_year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('half_day', 'Half Day')], default='present', max_length=10)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendance', to='teachers.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.attendancesession')),
            ],
            options={
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-session__date', 'student__user__first_name'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
