# Generated by Django 5.0 on 2025-08-23 11:34

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('assignment_type', models.CharField(choices=[('homework', 'Homework'), ('project', 'Project'), ('essay', 'Essay'), ('presentation', 'Presentation'), ('quiz', 'Quiz'), ('lab', 'Laboratory Work'), ('research', 'Research Paper'), ('other', 'Other')], default='homework', max_length=20)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigned Date')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('late_submission_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Late Submission Deadline')),
                ('total_marks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Marks')),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Weightage (%)')),
                ('allow_late_submission', models.BooleanField(default=False, verbose_name='Allow Late Submission')),
                ('late_submission_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Late Submission Penalty (%)')),
                ('allow_resubmission', models.BooleanField(default=False, verbose_name='Allow Resubmission')),
                ('max_resubmissions', models.PositiveIntegerField(default=1, verbose_name='Max Resubmissions')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Attachment')),
                ('rubric', models.JSONField(blank=True, default=dict, verbose_name='Grading Rubric')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('submission_closed', 'Submission Closed'), ('grading', 'Grading'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_type', models.CharField(choices=[('general', 'General'), ('feedback', 'Feedback'), ('question', 'Question'), ('clarification', 'Clarification')], default='general', max_length=20)),
                ('content', models.TextField(verbose_name='Content')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Private')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Assignment Comment',
                'verbose_name_plural': 'Assignment Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_text', models.TextField(blank=True, verbose_name='Submission Text')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Attachment')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marks Obtained')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentage')),
                ('grade', models.CharField(blank=True, max_length=2, verbose_name='Grade')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('rubric_scores', models.JSONField(blank=True, default=dict, verbose_name='Rubric Scores')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('late', 'Late'), ('graded', 'Graded'), ('returned', 'Returned'), ('resubmitted', 'Resubmitted')], default='submitted', max_length=20)),
                ('is_graded', models.BooleanField(default=False, verbose_name='Is Graded')),
                ('is_late', models.BooleanField(default=False, verbose_name='Is Late')),
                ('resubmission_count', models.PositiveIntegerField(default=0, verbose_name='Resubmission Count')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Graded At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-submission_date'],
            },
        ),
    ]
