version: '3.8'

services:
  # PostgreSQL Database (Production)
  db:
    image: postgres:15-alpine
    container_name: educore_postgres_prod
    environment:
      POSTGRES_DB: ${DB_NAME:-educore_ultra_prod}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-CHANGE_ME_STRONG_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    networks:
      - educore_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-educore_ultra_prod}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=512MB
      -c effective_cache_size=2GB
      -c maintenance_work_mem=128MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=32MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=8MB
      -c min_wal_size=2GB
      -c max_wal_size=8GB

  # Redis for caching and message broker (Production)
  redis:
    image: redis:7-alpine
    container_name: educore_redis_prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - educore_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

  # Django Backend Application (Production)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: educore_backend_prod
    environment:
      - DJANGO_SETTINGS_ENV=prod
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-CHANGE_ME_STRONG_PASSWORD}@db:5432/${DB_NAME:-educore_ultra_prod}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-CHANGE_ME_SUPER_RANDOM_64CHARS_FOR_PRODUCTION}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-yourdomain.com,www.yourdomain.com,localhost}
    env_file:
      - env.production
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./backend/logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - educore_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # React Frontend Application (Production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${BACKEND_URL:-https://yourdomain.com/api}
    container_name: educore_frontend_prod
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - educore_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker (Production)
  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: educore_celery_worker_prod
    environment:
      - DJANGO_SETTINGS_ENV=prod
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-CHANGE_ME_STRONG_PASSWORD}@db:5432/${DB_NAME:-educore_ultra_prod}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-CHANGE_ME_SUPER_RANDOM_64CHARS_FOR_PRODUCTION}
      - DEBUG=False
    env_file:
      - env.production
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./backend/logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - educore_network
    restart: unless-stopped
    command: celery -A core worker -l info --concurrency=4 --max-tasks-per-child=1000

  # Celery Beat (Scheduler) (Production)
  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: educore_celery_beat_prod
    environment:
      - DJANGO_SETTINGS_ENV=prod
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-CHANGE_ME_STRONG_PASSWORD}@db:5432/${DB_NAME:-educore_ultra_prod}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-CHANGE_ME_SUPER_RANDOM_64CHARS_FOR_PRODUCTION}
      - DEBUG=False
    env_file:
      - env.production
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./backend/logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - educore_network
    restart: unless-stopped
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: educore_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - frontend
      - backend
    networks:
      - educore_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus Monitoring (Production)
  prometheus:
    image: prom/prometheus:latest
    container_name: educore_prometheus_prod
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    networks:
      - educore_network
    restart: unless-stopped

  # Grafana Dashboard (Production)
  grafana:
    image: grafana/grafana:latest
    container_name: educore_grafana_prod
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-CHANGE_ME_GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SERVER_ROOT_URL=https://yourdomain.com/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - educore_network
    restart: unless-stopped

  # Node Exporter (System Metrics)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: educore_node_exporter_prod
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - educore_network
    restart: unless-stopped

  # PostgreSQL Exporter (Database Metrics)
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: educore_postgres_exporter_prod
    environment:
      - DATA_SOURCE_NAME=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-CHANGE_ME_STRONG_PASSWORD}@db:5432/${DB_NAME:-educore_ultra_prod}?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - educore_network
    restart: unless-stopped

  # Redis Exporter (Cache Metrics)
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: educore_redis_exporter_prod
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - educore_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  educore_network:
    driver: bridge
