# Generated by Django 5.0 on 2025-08-23 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('event_type', models.CharField(choices=[('academic', 'Academic'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=20, verbose_name='Event Type')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('venue', models.CharField(max_length=200, verbose_name='Venue')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('organizer', models.CharField(max_length=100, verbose_name='Organizer')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='Contact Phone')),
                ('target_audience', models.CharField(blank=True, max_length=200, verbose_name='Target Audience')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Participants')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is Public')),
                ('requires_registration', models.BooleanField(default=False, verbose_name='Requires Registration')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Registration Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date', '-start_time'],
                'indexes': [models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx'), models.Index(fields=['status'], name='events_even_status_5709b6_idx'), models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'), models.Index(fields=['is_public'], name='events_even_is_publ_e2e10e_idx')],
            },
        ),
    ]
