# Generated by Django 5.0 on 2025-08-23 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Mathematics, English, Science', max_length=100)),
                ('code', models.CharField(help_text='e.g., MATH101, ENG201', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('credits', models.PositiveIntegerField(default=1)),
                ('is_core', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
