# Generated by Django 5.0 on 2025-08-28 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., 2024-2025, Academic Year 2024', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(help_text='Start date of academic year')),
                ('end_date', models.DateField(help_text='End date of academic year')),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False, help_text='Current academic year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.PositiveIntegerField(default=1, help_text='Semester number'),
        ),
    ]
