# Generated by Django 5.0 on 2025-08-23 11:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Enrollment Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('graduated', 'Graduated'), ('dropped', 'Dropped')], default='active', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Class Enrollment',
                'verbose_name_plural': 'Class Enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Room Name')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Room Number')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='Building')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='Floor')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Capacity')),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('computer_lab', 'Computer Lab'), ('library', 'Library'), ('auditorium', 'Auditorium'), ('gymnasium', 'Gymnasium'), ('other', 'Other')], default='classroom', max_length=20, verbose_name='Room Type')),
                ('equipment', models.TextField(blank=True, verbose_name='Equipment')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Class Room',
                'verbose_name_plural': 'Class Rooms',
                'ordering': ['building', 'floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, verbose_name='Day of Week')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('period_number', models.PositiveIntegerField(verbose_name='Period Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_absences', models.PositiveIntegerField(default=20, verbose_name='Maximum Absences')),
                ('attendance_required', models.BooleanField(default=True, verbose_name='Attendance Required')),
                ('grading_system', models.CharField(choices=[('letter', 'Letter Grades'), ('percentage', 'Percentage'), ('gpa', 'GPA')], default='letter', max_length=20, verbose_name='Grading System')),
                ('pass_percentage', models.PositiveIntegerField(default=40, verbose_name='Pass Percentage')),
                ('allow_repeat', models.BooleanField(default=True, verbose_name='Allow Repeat')),
                ('max_repeats', models.PositiveIntegerField(default=2, verbose_name='Maximum Repeats')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Class Settings',
                'verbose_name_plural': 'Class Settings',
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=True, verbose_name='Is Compulsory')),
                ('weekly_hours', models.PositiveIntegerField(default=5, verbose_name='Weekly Hours')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Class Subject',
                'verbose_name_plural': 'Class Subjects',
                'ordering': ['class_obj', 'order', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Subject Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('optional', 'Optional'), ('extra_curricular', 'Extra Curricular')], default='core', max_length=50, verbose_name='Category')),
                ('grade_level', models.CharField(choices=[('primary', 'Primary'), ('middle', 'Middle'), ('high', 'High'), ('college', 'College'), ('all', 'All Levels')], default='all', max_length=20, verbose_name='Grade Level')),
                ('credit_hours', models.PositiveIntegerField(default=1, verbose_name='Credit Hours')),
                ('max_marks', models.PositiveIntegerField(default=100, verbose_name='Maximum Marks')),
                ('pass_marks', models.PositiveIntegerField(default=40, verbose_name='Pass Marks')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F', 'F')], default='C', max_length=5, verbose_name='Minimum Grade')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Is Mandatory')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Subject Prerequisite',
                'verbose_name_plural': 'Subject Prerequisites',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Class Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Class Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Class Capacity')),
                ('current_students', models.PositiveIntegerField(default=0, verbose_name='Current Students')),
                ('grade_level', models.CharField(choices=[('primary', 'Primary'), ('middle', 'Middle'), ('high', 'High'), ('college', 'College')], default='primary', max_length=20, verbose_name='Grade Level')),
                ('section', models.CharField(blank=True, max_length=10, verbose_name='Section')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_years.academicyear', verbose_name='Academic Year')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['grade_level', 'name', 'section'],
            },
        ),
    ]
