# Generated by Django 5.0 on 2025-08-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_years', '0001_initial'),
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Class Teacher'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_years.academicyear', verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classroom', verbose_name='Class Room'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_years.academicyear', verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='classes.class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classroom', verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='teachers.teacher', verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='classsettings',
            name='class_obj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='classes.class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_years.academicyear', verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='subjectprerequisite',
            name='prerequisite_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='classes.subject', verbose_name='Prerequisite Subject'),
        ),
        migrations.AddField(
            model_name='subjectprerequisite',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='classes.subject', verbose_name='Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='classenrollment',
            unique_together={('student', 'class_obj', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'academic_year', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_obj', 'subject', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('class_obj', 'day_of_week', 'period_number', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectprerequisite',
            unique_together={('subject', 'prerequisite_subject')},
        ),
    ]
